mapper:
  ros__parameters:
    machine_names:
      - M-DS
      - M-SS
      - M-BS
      - M-CS1
      - M-CS2
      - M-RS1
      - M-RS2
      - C-DS
      - C-BS
      - C-SS
      - C-RS1
      - C-RS2
      - C-CS1
      - C-CS2
      
